/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void detectBtnClick(GButton source, GEvent event) { //_CODE_:detectBtn:397567:
  portLabel.setText("Detecting pusher, please wait...");
  pusher = DetectPusher();
  if (pusher != null) {
    portLabel.setText(pusher.port);
    verLabel.setText(pusher.ver);
  } else {
    portLabel.setText("Pusher not found");
    verLabel.setText("");
  }
} //_CODE_:detectBtn:397567:

public void reflashButton_click1(GButton source, GEvent event) { //_CODE_:reflashButton:692070:
  println("reflashButton - GButton event occured " + System.currentTimeMillis()%10000000 );
  enterReflash();
  reflashLabel.setText("In reflash mode");
} //_CODE_:reflashButton:692070:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  if(frame != null)
    frame.setTitle("PixelPusher Configuration Tool");
  detectBtn = new GButton(this, 10, 10, 130, 30);
  detectBtn.setText("Detect PixelPusher");
  detectBtn.addEventHandler(this, "detectBtnClick");
  portLabel = new GLabel(this, 150, 20, 390, 20);
  portLabel.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  portLabel.setOpaque(false);
  verLabel = new GLabel(this, 550, 20, 80, 20);
  verLabel.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  verLabel.setOpaque(false);
  reflashButton = new GButton(this, 11, 51, 128, 36);
  reflashButton.setText("Enter reflash mode");
  reflashButton.addEventHandler(this, "reflashButton_click1");
  reflashLabel = new GLabel(this, 150, 61, 174, 20);
  reflashLabel.setOpaque(false);
}

// Variable declarations 
// autogenerated do not edit
GButton detectBtn; 
GLabel portLabel; 
GLabel verLabel; 
GButton reflashButton; 
GLabel reflashLabel; 

