/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void detectBtnClick(GButton source, GEvent event) { //_CODE_:detectBtn:397567:
  portLabel.setText("Detecting pusher, please wait...");
  pusher = DetectPusher();
  if (pusher != null) {
    portLabel.setText("Port: " + pusher.port);
    verLabel.setText("Version: "  + pusher.ver);
    configPanel.setVisible(true);
  } else {
    portLabel.setText("Pusher not found");
    verLabel.setText("");
    configPanel.setVisible(false);
  }
} //_CODE_:detectBtn:397567:

public void panel1_Click1(GPanel source, GEvent event) { //_CODE_:configPanel:481018:
  
} //_CODE_:configPanel:481018:

public void saveButtonClick(GButton source, GEvent event) { //_CODE_:saveButton:202835:
  writeConfig(pusher);
} //_CODE_:saveButton:202835:

public void custom_slider1_change1(GCustomSlider source, GEvent event) { //_CODE_:usbHoldoffSlider:271887:
  holdoffValueLabel.setText(usbHoldoffSlider.getValueS());
} //_CODE_:usbHoldoffSlider:271887:

public void fileselect_button1_click1(GButton source, GEvent event) { //_CODE_:fileselect_button1:368389:
  println("fileselect_button1 - GButton event occured " + System.currentTimeMillis()%10000000 );
  
  final JFileChooser fc = new JFileChooser(); 
  println("Selecting a file.");
  // in response to a button click: 
  int returnVal = fc.showOpenDialog(this); 

  if (returnVal == JFileChooser.APPROVE_OPTION) { 
    try {
      File file = fc.getSelectedFile(); 
      println(file.getCanonicalPath());
      filename = file.getCanonicalPath();
      pathLabel.setText(filename);
    } 
    catch (IOException ioe) {
      //
    }
  }
} //_CODE_:fileselect_button1:368389:

public void reflash_button1_click1(GButton source, GEvent event) { //_CODE_:reflash_button1:952778:
  println("reflash_button1 - GButton event occured " + System.currentTimeMillis()%10000000 );
  enterReflash(pusher);
  reflashLabel.setText("In reflash mode");
} //_CODE_:reflash_button1:952778:

public void remove_button1_click1(GButton source, GEvent event) { //_CODE_:remove_button1:409098:
  println("remove_button1 - GButton event occured " + System.currentTimeMillis()%10000000 );
  eraseConfig(pusher);
} //_CODE_:remove_button1:409098:

public void reboot_button1_click1(GButton source, GEvent event) { //_CODE_:reboot_button1:322829:
  println("reboot_button1 - GButton event occured " + System.currentTimeMillis()%10000000 );
  reboot(pusher);
} //_CODE_:reboot_button1:322829:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  if(frame != null)
    frame.setTitle("PixelPusher Configuration Tool");
  detectBtn = new GButton(this, 10, 10, 130, 30);
  detectBtn.setText("Detect PixelPusher");
  detectBtn.addEventHandler(this, "detectBtnClick");
  portLabel = new GLabel(this, 150, 20, 340, 20);
  portLabel.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  portLabel.setOpaque(false);
  verLabel = new GLabel(this, 500, 20, 130, 20);
  verLabel.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  verLabel.setOpaque(false);
  configPanel = new GPanel(this, 12, 60, 620, 410, "Pusher Config");
  configPanel.setCollapsible(false);
  configPanel.setDraggable(false);
  configPanel.setText("Pusher Config");
  configPanel.setOpaque(true);
  configPanel.addEventHandler(this, "panel1_Click1");
  label1 = new GLabel(this, 10, 30, 140, 20);
  label1.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  label1.setText("USB Reset Holdoff (ms)");
  label1.setOpaque(false);
  saveButton = new GButton(this, 524, 371, 80, 30);
  saveButton.setText("Save");
  saveButton.setTextBold();
  saveButton.addEventHandler(this, "saveButtonClick");
  usbHoldoffSlider = new GCustomSlider(this, 160, 30, 350, 20, "grey_blue");
  usbHoldoffSlider.setLimits(1020, 0, 1020);
  usbHoldoffSlider.setNbrTicks(255);
  usbHoldoffSlider.setStickToTicks(true);
  usbHoldoffSlider.setNumberFormat(G4P.INTEGER, 0);
  usbHoldoffSlider.setOpaque(false);
  usbHoldoffSlider.addEventHandler(this, "custom_slider1_change1");
  holdoffValueLabel = new GLabel(this, 520, 30, 90, 20);
  holdoffValueLabel.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  holdoffValueLabel.setText("1020");
  holdoffValueLabel.setOpaque(false);
  fileselect_button1 = new GButton(this, 484, 324, 120, 30);
  fileselect_button1.setText("Select pixel.rc file");
  fileselect_button1.addEventHandler(this, "fileselect_button1_click1");
  pathLabel = new GLabel(this, 161, 329, 309, 20);
  pathLabel.setText("No file selected");
  pathLabel.setOpaque(false);
  reflash_button1 = new GButton(this, 484, 276, 120, 30);
  reflash_button1.setText("Enter reflash mode");
  reflash_button1.addEventHandler(this, "reflash_button1_click1");
  reflashLabel = new GLabel(this, 161, 281, 310, 20);
  reflashLabel.setOpaque(false);
  remove_button1 = new GButton(this, 485, 227, 119, 30);
  remove_button1.setText("Remove pixel.rc");
  remove_button1.addEventHandler(this, "remove_button1_click1");
  reboot_button1 = new GButton(this, 485, 180, 120, 30);
  reboot_button1.setText("Reboot");
  reboot_button1.addEventHandler(this, "reboot_button1_click1");
  configPanel.addControl(label1);
  configPanel.addControl(saveButton);
  configPanel.addControl(usbHoldoffSlider);
  configPanel.addControl(holdoffValueLabel);
  configPanel.addControl(fileselect_button1);
  configPanel.addControl(pathLabel);
  configPanel.addControl(reflash_button1);
  configPanel.addControl(reflashLabel);
  configPanel.addControl(remove_button1);
  configPanel.addControl(reboot_button1);
}

// Variable declarations 
// autogenerated do not edit
GButton detectBtn; 
GLabel portLabel; 
GLabel verLabel; 
GPanel configPanel; 
GLabel label1; 
GButton saveButton; 
GCustomSlider usbHoldoffSlider; 
GLabel holdoffValueLabel; 
GButton fileselect_button1; 
GLabel pathLabel; 
GButton reflash_button1; 
GLabel reflashLabel; 
GButton remove_button1; 
GButton reboot_button1; 

